# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_measure <- function(datamat, projmat, lastNeighbor) {
    .Call('_DRQM_c_measure', PACKAGE = 'DRQM', datamat, projmat, lastNeighbor)
}

c_klmeasure <- function(Data, pData, NeighborhoodSize = 20L) {
    .Call('_DRQM_c_klmeasure', PACKAGE = 'DRQM', Data, pData, NeighborhoodSize)
}

